; Listing generated by Microsoft (R) Optimizing Compiler Version 19.22.27706.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Алек\AppData\Local\Temp\.NETFramework,Version=v4.7.2.AssemblyAttributes.cpp"
